version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shinsekai_db
      MYSQL_USER: shinsekai_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: 009160040466.dkr.ecr.ap-northeast-2.amazonaws.com/shinsekai-server:latest
    container_name: shinsekai-server
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
