spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shinsekai_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: baebuseung@gmail.com #개인정보
    password: laer eehi hpeg exsj  #개인정보
    properties:
      auth: true
      starttls: true
      sslTrust: smtp.gmail.com

jwt:
  secret-key: "GIiFreBAKN4iXIP7V3/EaMkNYRLLX7CNXK9jf/8J7uo="
  token:
    access-expire-time: 1800000 # 30분
    refresh-expire-time: 1209600000  # 14일

toss:
  secret-key: test_sk_26DlbXAaV0MmMlkoQeAdrqY50Q9R
  confirm-url: https://api.tosspayments.com/v1/payments/confirm