spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shinsekai_db
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: "Q9uvg4o0QfZyVID+eLd2Zexh1p8a4ecQZVvraXfykdw="

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      type:
        descriptor:
          sql:
            BasicBinder: trace
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
