spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/shinsekai_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret-key: ${SECRET_KEY}
  token:
    access-expire-time: ((0 * 24 + 0) * 60 + 30) * 60 * 1000  # 0일 0시간 30분 (30분)
    refresh-expire-time: ((14 * 24 + 0) * 60 + 0) * 60 * 1000  # 14일 0시간 0분 (14일)


