spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/shinsekai_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${SECRET_KEY}
  token:
    access-expire-time: 1800000
    refresh-expire-time: 1209600000
