spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shinsekai_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      auth: true
      starttls: true
      sslTrust: smtp.gmail.com

jwt:
  secret-key: "secret-key"
  token:
    access-expire-time: 1800000 # 30분
    refresh-expire-time: 1209600000  # 14일

toss:
  secret-key: toss_secret_key
  confirm-url: https://api.tosspayments.com/v1/payments/confirm