spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/shinsekai_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  cloud:
    aws:
      s3:
        bucket: shinsekai-storage
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2

jwt:
  secret-key: ${SECRET_KEY}
  token:
    access-expire-time: 1800000 # 30분
    refresh-expire-time: 1209600000  # 14일


