spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shinsekai_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


jwt:
  secret-key: dev-secret-key
  token:
    access-expire-time: 1800000 # 30분
    refresh-expire-time: 1209600000  # 14일


